name: Deploy Infrastructure

on:
  push:
#    branches:
#      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  EKS_CLUSTER_NAME: eks_cluster_fiap_postech
  TF_LOG: "INFO" # "DEBUG"

jobs:
  deploy_terraform_aws:
    name: deploy_terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Terraform Format
        id: fmt
        run: terraform -chdir="./infra" fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform -chdir="./infra" init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform -chdir="./infra" validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform -chdir="./infra" plan -out=tfplan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        run: terraform -chdir="./infra" apply -input=false -auto-approve

  deploy_kubernetes_aws:
    needs: deploy_terraform_aws
    name: deploy_kubernetes_aws
    runs-on: ubuntu-latest

    steps:

      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v2

      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          kubectl apply -f infra-kubernetes/namespace.yaml
